version: 2
log-level: 1
root-markers:
  - .git/

tools:
  python-pylint: &python-pylint
    lint-command: 'pylint --msg-template="{msg_id}:{path}:{line:3d}:{column} [pylint:{msg_id}] {msg} ({symbol})"'
    lint-stdin: false
    lint-formats:
      - '%t%n:%f:%l:%c %m'
    format-command: black --quiet -
    format-stdin: true

  python-bandit: &python-bandit
    lint-command: 'bandit --format custom --msg-template "{relpath}:{line} [bandit:{test_id}]:{severity} {msg}"'
    lint-stdin: false
    lint-formats:
      - '%f:%l %m'

  qml-qmllint: &qml-qmllint
    lint-command: 'qmllint --check-unqualified'
    lint-stdin: false
    lint-formats:
      - '%f:%l : %m'

  cpp-clangformat: &cpp-clangformat
    format-command: 'clang-format'
    format-stdin: true

  json-jq: &json-jq
    lint-command: 'jq . '
    format-command: 'jq . '
    lint-stdin: true
    format-stdin: true

languages:
  python:
    - <<: *python-pylint
    - <<: *python-bandit
  json:
    - <<: *json-jq
  qml:
    - <<: *qml-qmllint
  cpp:
    - <<: *cpp-clangformat
  c:
    - <<: *cpp-clangformat
