---
version: 2
log-level: 1
root-markers:
  - .git/

tools:
  python-pylint: &python-pylint
    lint-command: 'pylint --msg-template="{msg_id}:{path}:{line:3d}:{column} [pylint:{msg_id}] {msg} ({symbol})"'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%t%n:%f:%l:%c %m'
    format-command: black --quiet -
    format-stdin: true

  python-pyright: &python-pyright
    lint-command: 'pyright'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%t%n:%f:%l:%c %m'
      - '%-P%f'
      - '  %#%l:%c - %# %tarning: %m'
      - '  %#%l:%c - %# %trror: %m'
      - '    %Eerror %m'
      - '    %C%\s%+%m'

  python-bandit: &python-bandit
    lint-command: 'bandit --skips B101 --format custom --msg-template "{relpath}:{line} [bandit:{test_id}]:{severity} {msg}"'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l %m'

  qml-qmllint: &qml-qmllint
    lint-command: 'qmllint --check-unqualified ${INPUT}'
    lint-stdin: false
    format-command: 'qmlformat ${INPUT}'
    format-stdin: false
    lint-formats:
      - '%f:%l : %m'

  cpp-clangformat: &cpp-clangformat
    format-command: 'clang-format'
    format-stdin: true

  cpp-clangcheck: &cpp-clangcheck
    lint-command: 'clang-check'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %m'

  json-jq: &json-jq
    format-command: 'jq . '
    format-stdin: true
    lint-command: 'jq . '
    lint-stdin: true
    lint-formats:
      - 'parse error: %m %l, column %c'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true
    ling-formats:
      - '%f:%l:%c: [%tarning] %m'
      - '%f:%l:%c: [%trror] %m'

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  any-completion: &any-completion
    completion-command: >-
      cat ${INPUT} | rg "\w+" --no-filename --no-column --no-line-number
      --only-matching | sort -u
    completion-stdin: false
    lint-source: "efm-langserver"

  any-custom-hover: &any-custom-hover
    hover-command: >-
      python3 ~/.dotfiles/vim/scripts/lsp_hover.py --hover ${INPUT}
    hover-stdin: false

languages:
  python:
    - <<: *python-pylint
    - <<: *python-bandit
    - <<: *any-completion
    - <<: *any-custom-hover
  json:
    - <<: *json-jq
    - <<: *any-completion
    - <<: *any-custom-hover
  yaml:
    - <<: *yaml-yamllint
    - <<: *any-completion
    - <<: *any-custom-hover
  qml:
    - <<: *qml-qmllint
    - <<: *any-completion
    - <<: *any-custom-hover
  cpp:
    - <<: *cpp-clangformat
    - <<: *cpp-clangcheck
    - <<: *any-completion
    - <<: *any-custom-hover
  c:
    - <<: *cpp-clangformat
    - <<: *cpp-clangcheck
    - <<: *any-completion
    - <<: *any-custom-hover
  lua:
    - <<: *lua-lua-format
    - <<: *any-completion
    - <<: *any-custom-hover
  _:
    - <<: *any-completion
    - <<: *any-custom-hover
