version: 2
log-level: 1
root-markers:
  - .git/

tools:
  python-pylint: &python-pylint
    lint-command: 'pylint --msg-template="{msg_id}:{path}:{line:3d}:{column} [pylint:{msg_id}] {msg} ({symbol})"'
    lint-stdin: false
    lint-formats:
      - '%t%n:%f:%l:%c %m'
    format-command: black --quiet -
    format-stdin: true

  python-bandit: &python-bandit
    lint-command: 'bandit --format custom --msg-template "{relpath}:{line} [bandit:{test_id}]:{severity} {msg}"'
    lint-stdin: false
    lint-formats:
      - '%f:%l %m'

  qml-qmllint: &qml-qmllint
    lint-command: 'qmllint --check-unqualified ${INPUT}'
    lint-stdin: false
    format-command: 'qmlformat ${INPUT}'
    format-stdin: false
    lint-formats:
      - '%f:%l : %m'

  cpp-clangformat: &cpp-clangformat
    format-command: 'clang-format'
    format-stdin: true

  cpp-clangcheck: &cpp-clangcheck
    lint-command: 'clang-check'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %m'

  json-jq: &json-jq
    format-command: 'jq . '
    format-stdin: true
    lint-command: 'jq . '
    lint-stdin: true
    lint-formats:
      - 'parse error: %m %l, column %c'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true
    ling-formats:
      - '%f:%l:%c: [%tarning] %m'
      - '%f:%l:%c: [%trror] %m'

languages:
  python:
    - <<: *python-pylint
    - <<: *python-bandit
  json:
    - <<: *json-jq
  yaml:
    - <<: *yaml-yamllint
  qml:
    - <<: *qml-qmllint
  cpp:
    - <<: *cpp-clangformat
    - <<: *cpp-clangcheck
  c:
    - <<: *cpp-clangformat
    - <<: *cpp-clangcheck
