vim.cmd([[augroup vimrc_filetypes]])
vim.cmd([[au!]])
vim.cmd([[autocmd BufNewFile,BufRead hfl.txt setlocal filetype=hfl]])
vim.cmd([[autocmd BufNewFile,BufRead qmldir setlocal filetype=qmldir]])
vim.cmd([[autocmd BufNewFile,BufRead *.qmltypes setlocal filetype=qmldir]])
vim.cmd([[autocmd BufNewFile,BufRead term://* setlocal filetype=terminal]])
vim.cmd([[autocmd TermOpen * setlocal filetype=terminal]])
vim.cmd([[autocmd BufNewFile,BufRead todo.txt setlocal filetype=todo]])
vim.cmd([[autocmd BufNewFile,BufRead *.todo setlocal filetype=todo]])
vim.cmd([[autocmd BufNewFile,BufRead *.http setlocal filetype=http]])
vim.cmd([[autocmd BufNewFile,BufRead CMakeLists.txt setlocal filetype=cmake]])
vim.cmd([[autocmd BufNewFile,BufRead *.mt setlocal filetype=tags]])
vim.cmd([[autocmd BufNewFile,BufRead *.qmlproject setlocal filetype=qml]])
vim.cmd([[augroup END]])
