#!pwsh

if ("$args" -eq "--submodules") {
    git submodule foreach 'git fetch --prune && git logpretty $(git rev-parse --abbrev-ref HEAD)..origin/$(git rev-parse --abbrev-ref HEAD) && echo "-----"'
}
else {
    git fetch --prune && git logpretty $(git rev-parse --abbrev-ref HEAD)..origin/$(git rev-parse --abbrev-ref HEAD)
}

# vim: filetype=ps1
